# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::DEBUGGER__::TrapInterceptor; end
module Rails::Command::Behavior::ClassMethods; end
module Rails::Generators::Migration::ClassMethods; end
